
package cmd

// This file is generated by main_build.go; DO NOT EDIT.

var (
	// GOPATH - GOPATH value at the time of build.
	GOPATH = "C:/Users/user/go"

	// GOROOT - GOROOT value at the time of build.
	GOROOT = "C:/Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.9.windows-amd64"

	// Version - version time.RFC3339.
	Version = "2025-10-17T09:02:03Z"

	// ReleaseTag - release tag in TAG.%Y-%m-%dT%H-%M-%SZ.
	ReleaseTag = "RELEASE.2025-10-17T09-02-03Z"

	// CommitID - latest commit id.
	CommitID = "7e3083be53a90bf184fa4a78942384743f3512d1"

	// ShortCommitID - first 12 characters from CommitID.
	ShortCommitID = "7e3083be53a9"
)
		