package cmd

// This file is generated by main_build.go; DO NOT EDIT.

var (
	// GOPATH - GOPATH value at the time of build.
	GOPATH = ""

	// GOROOT - GOROOT value at the time of build.
	GOROOT = ""

	// Version - version time.RFC3339.
	Version = "UNSUPPORTED.GOGET"

	// ReleaseTag - release tag in TAG.%Y-%m-%dT%H-%M-%SZ.
	ReleaseTag = "UNSUPPORTED.GOGET"

	// CommitID - latest commit id.
	CommitID = "UNSUPPORTED.GOGET"

	// ShortCommitID - first 12 characters from CommitID.
	ShortCommitID = "UNSUPPORTED.GOGET"
)
