### dependency licenses
Below are the licenses of every dependency module. \
This file is generated by [a template](license-dependencies.tpl), see [readme](../readme) for details.

| module | license |
| --- | --- |
{{- range . }}
| {{ .Name }} | [{{ .LicenseName }}]({{ .LicenseURL }}) |
{{- end }}